### ISSUE TITLE
mod crashes

### ISSUE THREAD

**Issue by sanblch** [TheGreyGhost/SpeedyTools#1]
---- Minecraft Crash Report ----
// Oops.

Time: 12/13/14 3:35 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: java.io.File.toPath()Ljava/nio/file/Path;
    at speedytools.serverside.backup.MinecraftSaveFolderBackups.<init>(MinecraftSaveFolderBackups.java:52)
    at speedytools.serverside.backup.MinecraftSaveFolderBackups.<init>(MinecraftSaveFolderBackups.java:42)
    at speedytools.serverside.actions.SpeedyToolServerActions.worldLoadEvent(SpeedyToolServerActions.java:254)
    at speedytools.serverside.ServerEventHandler.worldLoad(ServerEventHandler.java:17)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_6_ServerEventHandler_worldLoad_Load.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:73)
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 3.2.0-4-amd64
    Java Version: 1.6.0_27, Sun Microsystems Inc.
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Sun Microsystems Inc.
    Memory: 215582968 bytes (205 MB) / 419495936 bytes (400 MB) up to 954466304 bytes (910 MB)
    JVM Flags: 1 total; -Xmx1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 15, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 4 mods loaded, 4 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    FML{7.10.85.1230} [Forge Mod Loader](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Forge{10.13.2.1230} [Minecraft Forge](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    speedytoolsmod{2.1.0} [Build Faster Mod](BuildFaster-2-1-0-Minecraft1-7-10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 8; []
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Tanner78** [comment]
Game crashes in 1.7.10 when i select a structure to move
[crash-2017-06-15_22.04.29-client.txt](https://github.com/TheGreyGhost/SpeedyTools/files/1078909/crash-2017-06-15_22.04.29-client.txt)
[crash-2017-06-15_22.04.37-server.txt](https://github.com/TheGreyGhost/SpeedyTools/files/1078910/crash-2017-06-15_22.04.37-server.txt)
